trigger: none

pr:
  - main

pool:
  name: Self-Hosted
  demands: 
  - Terraform
  - AzCLI

variables:
  - group: bestrong-secrets

jobs:
  - job:
    displayName: Terraform validation
    steps:
      - checkout: self
        displayName: Repository checkout

      - script: |
          terraform --version
          terraform init
          terraform validate
          terraform plan \
          -var "mssql-admin-username=nazar" \
          -var "mssql-admin-password=1111" \
          -var "bestrong-client-id=ebe928f2-e9e8-4fb7-98fb-b6b5881afba4" \
          -var "bestrong-client-secret=vQw8Q~S_rohBf2ZTlGm9ktg07JjXCxEm6ph84diF" \
          -var "bestrong-tenant-id=51704c4d-dc2b-4937-b575-9fcb22746e5c" \
          -var "bestrong-subscription-id=fb11f4de-c923-4a3a-92e8-6bf3d7115bc7"
        displayName: 'Running terraform plan to test configuration'
        env:
          ARM_CLIENT_ID: $(bestrong-client-id)
          ARM_CLIENT_SECRET: $(bestrong-client-secret)
          ARM_TENANT_ID: $(bestrong-tenant-id)
          ARM_SUBSCRIPTION_ID: $(bestrong-subscription-id)
          MSSQL_ADMIN_USERNAME: $(mssql-admin-username)
          MSSQL_ADMIN_PASSWORD: $(mssql-admin-password)
